"""
14_arsenal_similarity.py

Purpose:
--------
Find pitchers with similar ARSENAL SHAPE -- not similar mechanics
(that's 13_pitcher_similarity.py) and not similar pitch quality
(that's paom_score) -- just: does the movement-space footprint of
these two arsenals look alike?

This is a benchmarking tool, not a recommendation-donor search.
Two pitchers with near-identical arsenal shape but very different
paom_score is itself an interesting dashboard finding -- it isolates
execution (Effectiveness/Command) from raw shape (Movement), since
this comp is built ONLY from shape.

Why no handedness restriction (unlike 13_pitcher_similarity.py):
-------------------------------------------------------------------
horizontal_coverage, vertical_coverage, hull_area, centroid_
dispersion, and avg_nn_distance are all reflection-invariant by
construction (this was deliberate when 09_movement_component.py
was built) -- they don't encode which direction the ball is
breaking, just how much space the arsenal covers and how it's
distributed. A lefty and a righty with genuinely similar arsenal
shape is a legitimate, useful comp for this purpose. p_throws is
still carried through as a column for optional filtering/color-
coding on the dashboard.

Method:
-------
1. Load the six geometry features already computed and validated
   in PAOM_movement_component.csv.
2. Standardize.
3. Fit NearestNeighbors -> top-K arsenal-shape comps per pitcher.
4. Fit PCA(n_components=2) for a 2D arsenal-shape map.

Output:
-------
PAOM_arsenal_similarity.csv        (long format: pitcher x comp x rank)
PAOM_arsenal_map_coordinates.csv   (one row per pitcher, x/y + features)
"""

import pandas as pd
import numpy as np

from sklearn.preprocessing import StandardScaler
from sklearn.neighbors import NearestNeighbors
from sklearn.decomposition import PCA

import warnings
warnings.filterwarnings("ignore")


# ============================================================
# SETTINGS
# ============================================================

MOVEMENT_FILE = "PAOM_movement_component.csv"
MASTER_FILE = "master_pitch_table_2025.csv"   # source of p_throws

SIMILARITY_OUTPUT = "PAOM_arsenal_similarity.csv"
MAP_OUTPUT = "PAOM_arsenal_map_coordinates.csv"

N_NEIGHBORS = 10

GEOMETRY_FEATURES = [
    "horizontal_coverage",
    "vertical_coverage",
    "velocity_range",
    "hull_area",
    "centroid_dispersion",
    "avg_nn_distance"
]


# ============================================================
# LOAD DATA
# ============================================================

print("Loading movement component...")

movement = pd.read_csv(MOVEMENT_FILE)

print(f"Loaded {len(movement):,} pitchers")

missing = [c for c in GEOMETRY_FEATURES if c not in movement.columns]

if missing:
    raise ValueError(
        f"Missing geometry features: {missing}. Make sure "
        f"PAOM_movement_component.csv was generated by the current "
        f"version of 09_movement_component.py."
    )

profile = movement[["player_name"] + GEOMETRY_FEATURES].dropna().copy()

print(f"Pitchers with complete geometry features: {len(profile):,}")


# ============================================================
# MERGE IN THROWING HAND (for optional dashboard filtering only)
# ============================================================

print("\nLoading throwing hand (p_throws) for reference...")

master = pd.read_csv(MASTER_FILE)

hand_lookup = (
    master
    .groupby("player_name")["p_throws"]
    .first()
    .reset_index()
)

profile = profile.merge(hand_lookup, on="player_name", how="left")


# ============================================================
# STANDARDIZE FEATURES
# ============================================================

scaler = StandardScaler()
X_scaled = scaler.fit_transform(profile[GEOMETRY_FEATURES])


# ============================================================
# NEAREST NEIGHBORS (ARSENAL SHAPE COMPS, BOTH HANDS TOGETHER)
# ============================================================

print("\nFitting nearest-neighbor arsenal comps...")

nn = NearestNeighbors(n_neighbors=N_NEIGHBORS + 1)
nn.fit(X_scaled)

distances, indices = nn.kneighbors(X_scaled)

comp_records = []

player_names = profile["player_name"].values
hands = profile["p_throws"].values

for i, player in enumerate(player_names):
    rank = 1
    for j, dist in zip(indices[i], distances[i]):
        if player_names[j] == player:
            continue
        comp_records.append({
            "player_name": player,
            "comp_player_name": player_names[j],
            "same_hand": hands[i] == hands[j],
            "rank": rank,
            "arsenal_distance": dist
        })
        rank += 1
        if rank > N_NEIGHBORS:
            break

similarity_output = pd.DataFrame(comp_records)

similarity_output.to_csv(SIMILARITY_OUTPUT, index=False)

print(f"Saved {len(similarity_output):,} pitcher-comp pairs")

print(
    f"\nShare of top comps that are same-handed (expect roughly "
    f"league handedness rate if shape is truly hand-agnostic): "
    f"{similarity_output['same_hand'].mean():.1%}"
)


# ============================================================
# 2D MAP PROJECTION (PCA)
# ============================================================

print("\nFitting 2D arsenal-shape map...")

pca = PCA(n_components=2)
coords = pca.fit_transform(X_scaled)

print(
    f"\nExplained variance: PC1 = {pca.explained_variance_ratio_[0]:.1%}, "
    f"PC2 = {pca.explained_variance_ratio_[1]:.1%}, "
    f"total = {pca.explained_variance_ratio_.sum():.1%}"
)

if pca.explained_variance_ratio_.sum() < 0.6:
    print(
        "\nNOTE: the 2D map captures less than 60% of total shape "
        "variance -- treat proximity on the map as a rough visual "
        "guide; the nearest-neighbor table above (full feature "
        "space) is the more precise source for actual comps."
    )

profile["map_x"] = coords[:, 0]
profile["map_y"] = coords[:, 1]

map_output = profile[
    ["player_name", "p_throws"] + GEOMETRY_FEATURES + ["map_x", "map_y"]
]

map_output.to_csv(MAP_OUTPUT, index=False)


# ============================================================
# SUMMARY
# ============================================================

print("\n==============================")
print("Arsenal Similarity Engine Saved")
print("==============================")

print(f"\nPitchers profiled: {len(profile):,}")

print("\nSample comps (first pitcher in the list)")
print("------------------------------------------")
sample_player = profile["player_name"].iloc[0]
print(
    similarity_output[
        similarity_output["player_name"] == sample_player
    ]
)

print("\nSaved:")
print(f"- {SIMILARITY_OUTPUT}")
print(f"- {MAP_OUTPUT}")
