"""
94_batch_precompute_historical_recommendations.py

Purpose:
--------
Pre-computes the historical-precedent engine's recommendations for
every real pitcher, once, and saves them to CSV files matching the
dashboard's existing load_*_recs() pattern (data_loader.py's
_safe_load convention -- one CSV, loaded and cached, not computed
live on page load).

WHY THIS EXISTS: recommend_arsenal_changes() fits several real
regressions per candidate per pitcher -- confirmed genuinely slow
at real dashboard scale (92/92b's multi-minute runs across a 60-
pitcher SAMPLE). Running this live on every Pitcher Detail page
load isn't viable. This runs it ONCE, for every real pitcher, and
saves the output for the dashboard to just read.

Uses the SAME real crosswalk (pybaseball's Chadwick register)
already validated in 90/91/92/93 -- converts the historical engine's
MLBAM player_id keying to PAOM's "Last, First" player_name keying,
so the output is directly joinable with every existing dashboard
data source.

Output:
-------
historical_recommendations.csv -- one row per (pitcher, rank),
matching PAOM_add_recommendations.csv's general shape (rank,
predicted values) but covering all four change types, not just ADD.

historical_recommendation_comps.csv -- one row per (pitcher, change_
type, pitch_type, comp_rank), the real historical comps behind each
recommendation, for the "show real comps by default" dashboard
requirement.
"""

import importlib.util
import sys
import time

import pandas as pd
import numpy as np
import pybaseball

import warnings
warnings.filterwarnings("ignore")


# ============================================================
# SETTINGS
# ============================================================

SEASON = 2025  # matches PAOM's own current-season scope
OUTCOME_METRIC = "xwoba_against"

RECOMMENDATIONS_OUTPUT = "historical_recommendations.csv"
COMPS_OUTPUT = "historical_recommendation_comps.csv"

N_COMPS_TO_SAVE = 5  # per candidate -- matches show_similar_comps'
                       # own default in 45


# ============================================================
# IMPORT FROM 45/60
# ============================================================

print("Loading recommendation engine (45) and Stage 1 integration (60)...")

rec_spec = importlib.util.spec_from_file_location(
    "similarity_recommendation_engine", "45_similarity_recommendation_engine.py"
)
rec_engine = importlib.util.module_from_spec(rec_spec)
sys.modules["similarity_recommendation_engine"] = rec_engine
rec_spec.loader.exec_module(rec_engine)

recommend_arsenal_changes = rec_engine.recommend_arsenal_changes
similarity_features = rec_engine.similarity_features
SIMILARITY_FEATURE_COLS = rec_engine.SIMILARITY_FEATURE_COLS

stage60_spec = importlib.util.spec_from_file_location(
    "stage1_all_change_types", "60_stage1_all_change_types.py"
)
stage60 = importlib.util.module_from_spec(stage60_spec)
sys.modules["stage1_all_change_types"] = stage60
stage60_spec.loader.exec_module(stage60)

predict_arsenal_change_with_stage1_all_types = stage60.predict_arsenal_change_with_stage1_all_types

# 96's swap prediction function -- REAL FIX: this was never actually
# wired in before, even though 45 itself supports it via the
# swap_prediction_fn parameter. Without this import and the
# corresponding call-site change below, SWAP candidates could never
# be generated by this batch script, regardless of whether 45 itself
# was correct.
swap_spec = importlib.util.spec_from_file_location(
    "swap_prediction", "96_swap_prediction.py"
)
swap_mod = importlib.util.module_from_spec(swap_spec)
sys.modules["swap_prediction"] = swap_mod
swap_spec.loader.exec_module(swap_mod)

predict_swap_effect = swap_mod.predict_swap_effect


# ============================================================
# CROSSWALK -- same as 90/91/92/93
# ============================================================

print("\nBuilding real player_id <-> PAOM-style name crosswalk...")

chadwick = pybaseball.chadwick_register().dropna(subset=["key_mlbam"])
chadwick["key_mlbam"] = chadwick["key_mlbam"].astype(int)
chadwick["paom_style_name"] = chadwick["name_last"] + ", " + chadwick["name_first"]
id_to_paom_name = dict(zip(chadwick["key_mlbam"], chadwick["paom_style_name"]))

print(f"Crosswalk built for {len(id_to_paom_name):,} real MLBAM player_ids")


# ============================================================
# TARGET POPULATION -- every real pitcher with a full profile
# in the current season
# ============================================================

target_pool = similarity_features[
    similarity_features["season"] == SEASON
].dropna(subset=SIMILARITY_FEATURE_COLS)

print(f"\n{len(target_pool):,} real pitchers in {SEASON} to process")
print("HONEST WARNING: this is a genuinely long-running batch job -- "
      "each pitcher requires multiple regression fits. Expect this "
      "to take real time (likely tens of minutes) across the full "
      "population.")


# ============================================================
# RUN, WITH ROBUST PER-PITCHER ERROR HANDLING
# ============================================================

recommendation_rows = []
comp_rows = []
n_success = 0
n_failed = 0

start_time = time.time()

for i, (_, target_row) in enumerate(target_pool.iterrows()):
    player_id = target_row["player_id"]
    season = target_row["season"]

    paom_name = id_to_paom_name.get(player_id)
    if paom_name is None:
        continue

    try:
        recommendations, result_objects = recommend_arsenal_changes(
            player_id, season, outcome_metric=OUTCOME_METRIC,
            add_prediction_fn=predict_arsenal_change_with_stage1_all_types,
            other_change_prediction_fn=predict_arsenal_change_with_stage1_all_types,
            swap_prediction_fn=predict_swap_effect
        )
    except Exception as e:
        n_failed += 1
        continue

    if len(recommendations) == 0:
        continue

    for _, rec_row in recommendations.iterrows():
        recommendation_rows.append({
            "player_name": paom_name,
            "player_id": player_id,
            "rank": rec_row.get("rank", None),
            "change_type": rec_row["change_type"],
            "pitch_type": rec_row["pitch_type"],
            "estimated_usage_delta": rec_row.get("estimated_usage_delta"),
            "predicted_outcome": rec_row["predicted_outcome"],
            "predicted_change": rec_row["predicted_change"],
            "n_historical_events": rec_row.get("n_historical_events"),
            "confidence_tier": rec_row.get("confidence_tier"),
            "method": rec_row.get("method"),
            "fallback_values_used": rec_row.get("fallback_values_used"),
            "exceeds_historical_precedent": rec_row.get("exceeds_historical_precedent"),
            "is_high_usage_drop": rec_row.get("is_high_usage_drop"),
        })

        key = (rec_row["change_type"], rec_row["pitch_type"])
        if rec_row["change_type"] != "NO_CHANGE" and key in result_objects:
            comp_group = result_objects[key].get("group")
            if comp_group is not None and len(comp_group) > 0:
                top_comps = comp_group.sort_values(
                    "similarity_weight", ascending=False
                ).head(N_COMPS_TO_SAVE)
                for comp_rank, (_, comp_row) in enumerate(top_comps.iterrows(), start=1):
                    if rec_row["change_type"] == "SWAP":
                        # swap comps have a different real schema --
                        # dropped_usage_pct_before is the most directly
                        # meaningful "usage" number (no single, real
                        # usage_pct_after applies to a combined swap
                        # the same way it does for a single change).
                        # comp_dropped_pitch_type/comp_added_pitch_type
                        # capture which real swap this specific comp
                        # actually made -- may differ from the target's
                        # own candidate pair, since comps are weighted
                        # by overall similarity, not just an exact pair
                        # match.
                        comp_rows.append({
                            "player_name": paom_name,
                            "change_type": rec_row["change_type"],
                            "pitch_type": rec_row["pitch_type"],
                            "comp_rank": comp_rank,
                            "comp_player_name": comp_row.get("player_name"),
                            "comp_season_from": comp_row.get("season_from"),
                            "comp_season_to": comp_row.get("season_to"),
                            "comp_usage_before": comp_row.get("dropped_usage_pct_before"),
                            "comp_usage_after": None,
                            "comp_dropped_pitch_type": comp_row.get("dropped_pitch_type"),
                            "comp_added_pitch_type": comp_row.get("added_pitch_type"),
                            "similarity_weight": comp_row.get("similarity_weight"),
                        })
                    else:
                        comp_rows.append({
                            "player_name": paom_name,
                            "change_type": rec_row["change_type"],
                            "pitch_type": rec_row["pitch_type"],
                            "comp_rank": comp_rank,
                            "comp_player_name": comp_row.get("player_name"),
                            "comp_season_from": comp_row.get("season_from"),
                            "comp_season_to": comp_row.get("season_to"),
                            "comp_usage_before": comp_row.get("usage_pct_before"),
                            "comp_usage_after": comp_row.get("usage_pct_after"),
                            "comp_dropped_pitch_type": None,
                            "comp_added_pitch_type": None,
                            "similarity_weight": comp_row.get("similarity_weight"),
                        })

    n_success += 1

    if (i + 1) % 50 == 0:
        elapsed = time.time() - start_time
        print(f"  Processed {i + 1:,} / {len(target_pool):,} pitchers "
              f"({elapsed/60:.1f} min elapsed, {n_success:,} succeeded, {n_failed:,} failed)")

total_elapsed = time.time() - start_time
print(f"\nDone in {total_elapsed/60:.1f} minutes. "
      f"{n_success:,} pitchers succeeded, {n_failed:,} failed.")


# ============================================================
# SAVE
# ============================================================

recommendations_df = pd.DataFrame(recommendation_rows)
comps_df = pd.DataFrame(comp_rows)

recommendations_df.to_csv(RECOMMENDATIONS_OUTPUT, index=False)
comps_df.to_csv(COMPS_OUTPUT, index=False)

print(f"\nSaved:")
print(f"- {RECOMMENDATIONS_OUTPUT} ({len(recommendations_df):,} rows, "
      f"{recommendations_df['player_name'].nunique():,} pitchers)")
print(f"- {COMPS_OUTPUT} ({len(comps_df):,} rows)")
